name: CI

on:
  push:
    tags:
      - '*'

jobs:
  openwrt:
    name: OpenWrt package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/luci-app-esfshell

      - name: Build OpenWrt package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64
          PACKAGES: luci-app-esfshell

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: EsurfingShell v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            bin/packages/x86_64/base/luci-*-esfshell*.ipk