name: CI

on:
  push:
    tags:
      - '*'

jobs:
  openwrt:
    name: OpenWrt package
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/luci-app-esfshell

      - name: Setup version code
        run: |
          sed -i 's/PKG_VERSION:=master/PKG_VERSION:=v${{ github.ref_name }}/' luci-app-esfshell/Makefile
          sed -i 's/PKG_RELEASE:=1/PKG_RELEASE:=${{ github.run_number }}/' luci-app-esfshell/Makefile

      - name: Build OpenWrt package
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: x86_64-master
          PACKAGES: luci-app-esfshell

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: EsurfingShell v${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true
          files: |
            bin/packages/x86_64/action/*.ipk